{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "apex-os.fullname" . }}-api
  labels:
    {{- include "apex-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "apex-os.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "apex-os.fullname" . }}-web
  labels:
    {{- include "apex-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "apex-os.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
