apiVersion: v1
kind: Service
metadata:
  name: apex-backend
  namespace: apex-os
  labels:
    app: apex-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: apex-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None
