apiVersion: v1
kind: Service
metadata:
  name: apex-frontend
  namespace: apex-os
  labels:
    app: apex-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: apex-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: None
