apiVersion: v1
kind: Secret
metadata:
  name: apex-secrets
  namespace: apex-os
  labels:
    app: apex-os
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvYXBleF9vcw==
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  JWT_SECRET: Y2hhbmdlLW1lLXByb2R1Y3Rpb24tc2VjcmV0LWtleS0yNTYtYml0cw==
  API_KEY: Y2hhbmdlLW1lLXByb2R1Y3Rpb24tYXBpLWtleQ==
  ENCRYPTION_KEY: Y2hhbmdlLW1lLXByb2R1Y3Rpb24tZW5jcnlwdGlvbi1rZXk=
  SMTP_PASSWORD: Y2hhbmdlLW1lLXNtdHAtcGFzc3dvcmQ=
  S3_ACCESS_KEY: Y2hhbmdlLW1lLXMzLWFjY2Vzcy1rZXk=
  S3_SECRET_KEY: Y2hhbmdlLW1lLXMzLXNlY3JldC1rZXk=
