"""Initial schema for all APEX-OS modules.

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-10-03 00:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(100), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(200), nullable=True),
        sa.Column("role", sa.Enum("ADMIN","MANAGER","ACCOUNTANT","VIEWER", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("email"), sa.UniqueConstraint("username"))
    op.create_table("accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("account_number", sa.String(50), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE","FROZEN","CLOSED", name="account_status"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("account_number"))
    op.create_table("transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("type", sa.Enum("DEBIT","CREDIT","TRANSFER","REFUND", name="transaction_type"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("crm_contacts",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("phone", sa.String(50), nullable=True),
        sa.Column("company", sa.String(200), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("crm_deals",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("stage", sa.String(50), nullable=False),
        sa.Column("contact_id", sa.String(36), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["crm_contacts.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("crm_pipelines",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("deal_ids", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_products",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("sku", sa.String(100), nullable=False),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("category", sa.String(50), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.Column("unit_of_measure", sa.String(20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reorder_point", sa.Integer(), nullable=True),
        sa.Column("reorder_quantity", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_stock_items",
        sa.Column("product_id", sa.String(36), nullable=False),
        sa.Column("location", sa.String(100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("reserved_quantity", sa.Integer(), nullable=True),
        sa.Column("lot_number", sa.String(100), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["inventory_products.id"]),
        sa.PrimaryKeyConstraint("product_id", "location"))
    op.create_table("inventory_stock_movements",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("product_id", sa.String(36), nullable=False),
        sa.Column("location", sa.String(100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(10), nullable=False),
        sa.Column("reference", sa.String(100), nullable=True),
        sa.Column("unit_cost", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["inventory_products.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_purchase_orders",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("supplier_id", sa.String(36), nullable=False),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("order_date", sa.DateTime(), nullable=True),
        sa.Column("expected_date", sa.DateTime(), nullable=True),
        sa.Column("received_date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_purchase_order_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("po_id", sa.String(36), nullable=False),
        sa.Column("product_id", sa.String(36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.Column("received_quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["po_id"], ["inventory_purchase_orders.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["inventory_products.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_sales_orders",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=False),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("order_date", sa.DateTime(), nullable=True),
        sa.Column("required_date", sa.DateTime(), nullable=True),
        sa.Column("shipped_date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("inventory_sales_order_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("so_id", sa.String(36), nullable=False),
        sa.Column("product_id", sa.String(36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("fulfilled_quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["so_id"], ["inventory_sales_orders.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["inventory_products.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("projects",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("tasks",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("project_id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("dependencies", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("completion_percentage", sa.Float(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("resources",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("type", sa.String(20), nullable=True),
        sa.Column("capacity", sa.Float(), nullable=True),
        sa.Column("cost_rate", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(20), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("time_entries",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("task_id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("hours", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("billable", sa.Boolean(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_plans",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("billing_cycle", sa.String(20), nullable=True),
        sa.Column("features", sa.Text(), nullable=True),
        sa.Column("usage_limits", sa.Text(), nullable=True),
        sa.Column("overage_rates", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_subscriptions",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=False),
        sa.Column("plan_id", sa.String(36), nullable=False),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("trial_end", sa.DateTime(), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["plan_id"], ["billing_plans.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_usage_records",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=False),
        sa.Column("subscription_id", sa.String(36), nullable=False),
        sa.Column("metric", sa.String(100), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["subscription_id"], ["billing_subscriptions.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_invoices",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=False),
        sa.Column("subscription_id", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=True),
        sa.Column("tax", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["subscription_id"], ["billing_subscriptions.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_invoice_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.String(36), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["billing_invoices.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_payments",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("invoice_id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("method", sa.String(30), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("transaction_id", sa.String(100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["billing_invoices.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("billing_dunning_records",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=False),
        sa.Column("invoice_id", sa.String(36), nullable=False),
        sa.Column("subscription_id", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("actions", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["billing_invoices.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("ecommerce_customers",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("ecommerce_products",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("sku", sa.String(100), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("image_url", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("ecommerce_orders",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=True),
        sa.Column("tax", sa.Float(), nullable=True),
        sa.Column("shipping_cost", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("payment_id", sa.String(36), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["ecommerce_customers.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("ecommerce_order_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(36), nullable=False),
        sa.Column("product_id", sa.String(36), nullable=True),
        sa.Column("product_name", sa.String(300), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["ecommerce_orders.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("ecommerce_payments",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("order_id", sa.String(36), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("method", sa.String(30), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("transaction_id", sa.String(100), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["ecommerce_orders.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("accounting_accounts",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("account_type", sa.String(20), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("parent_id", sa.String(36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["accounting_accounts.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("accounting_journal_entries",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference", sa.String(100), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("accounting_transactions",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("journal_entry_id", sa.String(36), nullable=True),
        sa.Column("account_id", sa.String(36), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("reference", sa.String(100), nullable=True),
        sa.ForeignKeyConstraint(["journal_entry_id"], ["accounting_journal_entries.id"]),
        sa.ForeignKeyConstraint(["account_id"], ["accounting_accounts.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("accounting_invoices",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("customer_id", sa.String(36), nullable=True),
        sa.Column("issue_date", sa.DateTime(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("accounting_invoice_line_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.String(36), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("discount_percent", sa.Float(), nullable=True),
        sa.Column("tax_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["accounting_invoices.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_email_templates",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("subject", sa.String(300), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_campaigns",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("subject", sa.String(300), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("segments", sa.Text(), nullable=True),
        sa.Column("template_id", sa.String(36), nullable=True),
        sa.Column("metrics", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["template_id"], ["marketing_email_templates.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_leads",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("source", sa.String(100), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_nurture_sequences",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_nurture_steps",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("sequence_id", sa.String(36), nullable=True),
        sa.Column("email_template_id", sa.String(36), nullable=True),
        sa.Column("delay_days", sa.Integer(), nullable=True),
        sa.Column("condition", sa.String(200), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["sequence_id"], ["marketing_nurture_sequences.id"]),
        sa.ForeignKeyConstraint(["email_template_id"], ["marketing_email_templates.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_lead_enrollments",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("lead_id", sa.String(36), nullable=True),
        sa.Column("sequence_id", sa.String(36), nullable=True),
        sa.Column("current_step", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("enrolled_at", sa.DateTime(), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["marketing_leads.id"]),
        sa.ForeignKeyConstraint(["sequence_id"], ["marketing_nurture_sequences.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_ab_tests",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("winner_variant_id", sa.String(36), nullable=True),
        sa.Column("confidence_level", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("marketing_ab_variants",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("test_id", sa.String(36), nullable=True),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("subject", sa.String(300), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("metrics", sa.Text(), nullable=True),
        sa.Column("traffic_allocation", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["test_id"], ["marketing_ab_tests.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("notifications",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("title", sa.String(300), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("channels", sa.Text(), nullable=True),
        sa.Column("recipients", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(20), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("template_id", sa.String(36), nullable=True),
        sa.Column("template_data", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.Column("sent_at", sa.Float(), nullable=True),
        sa.Column("delivered_at", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("hr_employees",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(200), nullable=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("department", sa.String(100), nullable=True),
        sa.Column("position", sa.String(200), nullable=True),
        sa.Column("salary", sa.Float(), nullable=True),
        sa.Column("hire_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("hr_leave_records",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("employee_id", sa.String(36), nullable=True),
        sa.Column("leave_type", sa.String(50), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("hr_payroll_records",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("employee_id", sa.String(36), nullable=True),
        sa.Column("period_start", sa.DateTime(), nullable=True),
        sa.Column("period_end", sa.DateTime(), nullable=True),
        sa.Column("gross_pay", sa.Float(), nullable=True),
        sa.Column("deductions", sa.Float(), nullable=True),
        sa.Column("net_pay", sa.Float(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"))
    op.create_table("hr_performance_reviews",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("employee_id", sa.String(36), nullable=True),
        sa.Column("review_period", sa.String(50), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("goals", sa.Text(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("reviewer_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"]),
        sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for t in ["hr_performance_reviews","hr_payroll_records","hr_leave_records","hr_employees",
              "notifications","marketing_ab_variants","marketing_ab_tests","marketing_lead_enrollments",
              "marketing_nurture_steps","marketing_nurture_sequences","marketing_leads",
              "marketing_campaigns","marketing_email_templates","accounting_invoice_line_items",
              "accounting_invoices","accounting_transactions","accounting_journal_entries",
              "accounting_accounts","ecommerce_payments","ecommerce_order_items","ecommerce_orders",
              "ecommerce_products","ecommerce_customers","billing_dunning_records","billing_payments",
              "billing_invoice_lines","billing_invoices","billing_usage_records","billing_subscriptions",
              "billing_plans","time_entries","resources","tasks","projects",
              "inventory_sales_order_lines","inventory_sales_orders","inventory_purchase_order_lines",
              "inventory_purchase_orders","inventory_stock_movements","inventory_stock_items",
              "inventory_products","crm_pipelines","crm_deals","crm_contacts",
              "audit_logs","transactions","accounts","users"]:
        op.drop_table(t)
    for e in ["user_role","account_status","transaction_type"]:
        sa.Enum(name=e).drop(op.get_bind(), checkfirst=False)
